baseURL = "http://sgsa.berkeley.edu/"
languageCode = "en-us"
title = "SGSA"
theme = "hugo-theme-learn"

[params]
  description = "UC Berkeley Statistics Graduate Student Association"
  disableSearch = true
  disableInlineCopyToClipBoard = true
  copyright = "SGSA"
  showVisitedLinks = false
  author = "SGSA"
  themeVariant = "blue"
